runtime: nodejs20 # replace with your Node.js version
instance_class: F2 # choose an instance class based on your needs
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
env_variables:
  KEY_FILE: ./serviceAccountKey.json
  PROJECT_ID: 'secucare-406900'
  BUCKET_NAME: 'secucare'