runtime: nodejs20 # replace with your Node.js version
service: flex
instance_class: F2 # choose an instance class based on your needs
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
handlers:
- url: /
  script: server.js